name: eyp_cooking_app
description: cooking app for children

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutterfl
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+6


environment:
    sdk: ">=2.10.0 <3.0.0"

dependencies:
    flutter:
        sdk: flutter
    grouped_buttons: ^1.0.4
    #firebase_database: ^4.0.0
    auto_size_text: ^2.1.0
    flutter_signin_button: ^2.0.0
    path_provider: ^2.0.7
    google_sign_in: ^4.5.6
    google_fonts: ^2.1.0
    cloud_firestore: ^3.1.0
    file_picker: ^4.0.3
    firebase_auth: 3.1.4
    firebase_core: ^1.6.0
    firebase_storage: ^10.0.3
    bordered_text: ^2.0.0
    ndialog: ^4.1.0
    roundcheckbox: ^2.0.1+2
    url_launcher: ^6.0.5
    flick_video_player: ^0.3.1
    video_player: ^2.1.13
    simple_animations: ^3.1.1
    # The following adds the Cupertino Icons font to your application.
    # Use with the CupertinoIcons class for iOS style icons.
    cupertino_icons: ^1.0.2
    carousel_slider: ^3.0.0
    provider: ^5.0.0
    connectivity: ^3.0.6
    connectivity_for_web: ^0.4.0+1
    firebase_app_check: ^0.0.3
    loading: ^1.0.2
    image_picker: ^0.8.4+4





dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_launcher_icons: ^0.9.2

flutter_icons:
    android: true
    ios: true
    image_path: "assets/eyplogo2.png"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

    # The following line ensures that the Material Icons font is
    # included with your application, so that you can use the icons in
    # the material Icons class.
    fonts:
        - family: FRED
          fonts:
              - asset: assets/fonts/FredokaOne-Regular.ttf
    uses-material-design: true
    assets:
        - images/eyplogo.png
        - images/Spinner.gif

    #    - family: Bal
    #      fonts:
    #        - asset: fonts/BalsamiqSans-Regular.ttf
    #    - family: Acme
    #      fonts:
    #        - asset: fonts/Acme-Regular.ttf


    #    - family: Trajan Pro
    #      fonts:
    #        - asset: fonts/TrajanPro.ttf
    #        - asset: fonts/TrajanPro_Bold.ttf
    #          weight: 700
    #
    # For details regarding fonts from package dependencies,
    # see https://flutter.dev/custom-fonts/#from-packages